### PR TITLE
can now add a (optional) reason to the restart and shutdown commands

### LINKED ISSUE #53: add optional message to restart and shutdown
I'd like to have this because I often restart bot in live org for updates. 

It would be nice if the bot could broadcast a reason to channels why it is being restarted or shutdown so people are not left without answers why it was done.

### PR DESCRIPTION
**Pull request by jroovers**
resolves #53 

Added optional reason parameter to shutdown and restart commands
Updated existing events to send reason if one was set

### CODE REVIEW

**Comment by jroovers** [comment]
Where exactly would I use that? I agree there is a lot of duplicate code here and I'm happy to reduce it!

I've given this some thought and this is what I came up with:

```python
def _format_message(self, restart, reason):
if restart:
    if reason:
        # return restart message with reason
    else:
        # return restart message
else:
    if reason:
        # return shutdown message with reason
    else:
        # return shutdown message

@event(event_type=SHUTDOWN_EVENT, description="Notify org channel on shutdown/restart")
    def notify_org_channel_shutdown_event(self, event_type, event_data):
            self.bot.send_org_message(self._format_message(event_type.restart, event_data.reason), fire_outgoing_event=False)
```

**Comment by bigwheels16** [comment]
yeah that should work.  I count four places you could use that method: once in each of the shutdown event handlers, once in the restart command, and once in the shutdown command.

**Comment by jroovers** [comment]
Updated

**Comment by bigwheels16** [comment]
great! that looks a lot cleaner

**Pull request merged**
