### PR TITLE
added auno command (and an aunoid command, had issues with id as const)

### PR DESCRIPTION
**Pull request by KristinHansen**
iz nice

I think the multiple results implementation went better than expected

### CODE REVIEW

**Comment by bigwheels16** [comment]
Looks good, a couple things tho.
1) The regexes for command parameters are tested in the order they appear in the file, which is why you had trouble with the id version of the command.  If you put that version of the command first in the file then it should work.  I really do not want to have two different commands to support the same function.
2) I don't think having the QL param is useful here.  The comments on auno don't depend on QL, only item id, so we should remove the QL param from the !auno command.

**Comment by KristinHansen** [comment]
Yeah, I did think of trying to just move it up, I'll do that and test it. Just thought it seemed too simple a fix to work around it.

Unfortunately, auno do hold comments separate for an item where lowid != highid, that's why I added the ql parameter.
Just as an example:
https://auno.org/ao/db.php?id=246645
https://auno.org/ao/db.php?id=246646

**Comment by KristinHansen** [comment]
The alternative to a 2nd command is to just use the `text.make_item`-method, and then use that itemref for the comments link.
```
for i, item in enumerate(items):
    itemref = self.text.make_item(item.lowid, item.highid, ql or item.highql, item.name)
    comments_link = self.text.make_chatcmd("comments", "/tell <myname> auno %s" % itemref
```

**Comment by bigwheels16** [comment]
I like the idea of removing the second command handler and adding a link to !items output.  I think that would be a better option.

Still, the QL for !auno should be removed.  It should be called like this: !auno <item_id>

Regarding the Combined Armor example, we could have it check the items db and pull comments for both the low and high ids, and merge them into a single output.  So for instance, !auno 246645 and !auno 246646 would both return the same output.  If it doesn't find a result in the items db for that item id, it should still call out to auno.org with the single item id, since the items db does not contain every item.

**Comment by KristinHansen** [comment]
Ah yes, I'll just fetch the comments for both id's. I'll have that fixed in the next commit.

**Pull request merged**
